# Generated by Django 4.0.1 on 2022-01-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
